In [18]:
import numpy as np

In [19]:
# 1
print("\nEjercicio 1\n")
print(np.arange(0, 101, 4))


Ejercicio 1

[  0   4   8  12  16  20  24  28  32  36  40  44  48  52  56  60  64  68
  72  76  80  84  88  92  96 100]


In [20]:
# 2
print("\nEjercicio 2\n")
print(np.arange(20).reshape(5, 4))


Ejercicio 2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [21]:
# 3
print("\nEjercicio 3\n")
array = np.arange(5)
print(array)
print(np.flip(array))


Ejercicio 3

[0 1 2 3 4]
[4 3 2 1 0]


In [22]:
# 4
print("\nEjercicio 4\n")
array = np.arange(9).reshape(3, 3)
print(array)
print(np.flip(array, 0))


Ejercicio 4

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [23]:
# 5
print("\nEjercicio 5\n")
array = np.arange(16, step=2).reshape(2, 4)
print(array)
print(np.mean(array, axis=0))


Ejercicio 5

[[ 0  2  4  6]
 [ 8 10 12 14]]
[ 4.  6.  8. 10.]


In [24]:
# 6
print("\nEjercicio 6\n")
array = np.arange(12)
print(array)
print(array.reshape(4, 3)) 


Ejercicio 6

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [25]:
# 7
print("\nEjercicio 7\n")
def transformArrayIntoSquareMatrix(array):
    side = int(array.size ** 0.5)
    if(side * side == array.size):
        print(array.reshape(side, side))
    else:
        print("The array can't be transformed into a square matrix")

array = np.arange(12)
print(array)
transformArrayIntoSquareMatrix(array)
    
array2 = np.arange(16)
print(array2)
transformArrayIntoSquareMatrix(array2)


Ejercicio 7

[ 0  1  2  3  4  5  6  7  8  9 10 11]
The array can't be transformed into a square matrix
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [26]:
# 8
print("\nEjercicio 8\n")
array = np.arange(16, step=2).reshape(2, 4)
print(array)
print(np.max(array, axis=1))


Ejercicio 8

[[ 0  2  4  6]
 [ 8 10 12 14]]
[ 6 14]


In [27]:
# 9
print("\nEjercicio 9\n")
array = np.random.randint(0, 10, 20)
print(array)
print(np.unique(array, return_counts=True))


Ejercicio 9

[6 5 5 8 0 5 9 7 9 8 5 0 1 8 7 2 1 3 0 0]
(array([0, 1, 2, 3, 5, 6, 7, 8, 9]), array([4, 2, 1, 1, 4, 1, 2, 3, 2], dtype=int64))


In [28]:
# 10
print("\nEjercicio 10\n")
array = np.arange(12).reshape(4, 3)
print(array)
mean = np.mean(array, axis=0)
std = np.std(array, axis=0)
print("Media: ", mean)
print("Desv: ", std)
print((array - mean) / std)


Ejercicio 10

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Media:  [4.5 5.5 6.5]
Desv:  [3.35410197 3.35410197 3.35410197]
[[-1.34164079 -1.34164079 -1.34164079]
 [-0.4472136  -0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079  1.34164079]]


In [29]:
# 11
print("\nEjercicio 11\n")
array = np.arange(1, 24, 2).reshape(4, 3)
print(array)
mean = np.mean(array, axis=1, keepdims=True)
std = np.std(array, axis=1, keepdims=True)
print("Media: ", mean)
print("Desv: ", std)
print((array - mean) / std)


Ejercicio 11

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]
 [19 21 23]]
Media:  [[ 3.]
 [ 9.]
 [15.]
 [21.]]
Desv:  [[1.63299316]
 [1.63299316]
 [1.63299316]
 [1.63299316]]
[[-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]]


In [30]:
# 12
print("\nEjercicio 12\n")
array = np.random.randint(0, 10, 12).reshape(4, 3)
print(array)
print("maximo: ", np.unravel_index(np.argmax(array), array.shape))
print("minimo: ", np.unravel_index(np.argmin(array), array.shape))


Ejercicio 12

[[1 0 8]
 [0 8 5]
 [5 8 3]
 [2 2 9]]
maximo:  (3, 2)
minimo:  (0, 1)


In [31]:
# 13
print("\nEjercicio 13\n")
array = np.random.randint(0, 10, 12).reshape(4, 3)
print(array)
orden = np.argsort(array[:, 0])
print(orden)
print(array[orden])


Ejercicio 13

[[3 2 4]
 [0 3 0]
 [1 0 7]
 [5 0 4]]
[1 2 0 3]
[[0 3 0]
 [1 0 7]
 [3 2 4]
 [5 0 4]]


In [32]:
# 14
print("\nEjercicio 14\n")
array = np.random.normal(size=35).reshape(7, 5)
array[array < 0] = 0
print(array)


Ejercicio 14

[[0.         0.         0.23136471 0.28438201 0.95321886]
 [0.40168636 0.71738076 0.08574733 0.         0.        ]
 [0.         1.18413451 0.24213137 1.3062799  0.49079854]
 [1.50698234 0.         0.         0.         0.21480551]
 [0.         0.         2.319082   0.         0.        ]
 [0.70829907 0.         0.         0.85923863 0.        ]
 [0.         0.         0.         0.17513472 0.        ]]


In [33]:
# 15
print("\nEjercicio 15\n")
array = np.random.randint(0, 100, 10)
print(array)
k = np.random.randint(2, 3)
print(k)
array = np.argsort(array)
print(array[-k:])


Ejercicio 15

[ 9  7 97 91 80 54  2  8  9 31]
2
[3 2]


In [34]:
# 16
print("\nEjercicio 16\n")
array = np.random.uniform(0, 1, 42).reshape(6, 7)
print(array)
array[:, :2] = 0
array[:, -3:] = 1
print(array)


Ejercicio 16

[[0.75062252 0.92430751 0.38784008 0.09967952 0.69107369 0.00422017
  0.08513551]
 [0.74515346 0.57919622 0.98963088 0.50525393 0.5354683  0.27251008
  0.48114415]
 [0.47313743 0.69307891 0.0163285  0.1466051  0.75611618 0.91879769
  0.56043158]
 [0.00194677 0.07619236 0.80197841 0.08593029 0.95983671 0.51334947
  0.76564401]
 [0.962745   0.40228384 0.54697187 0.80939607 0.77763826 0.98493848
  0.31833717]
 [0.23364934 0.37461627 0.43021079 0.0685986  0.89717226 0.774883
  0.25407355]]
[[0.         0.         0.38784008 0.09967952 1.         1.
  1.        ]
 [0.         0.         0.98963088 0.50525393 1.         1.
  1.        ]
 [0.         0.         0.0163285  0.1466051  1.         1.
  1.        ]
 [0.         0.         0.80197841 0.08593029 1.         1.
  1.        ]
 [0.         0.         0.54697187 0.80939607 1.         1.
  1.        ]
 [0.         0.         0.43021079 0.0685986  1.         1.
  1.        ]]
